// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// mediate_helper
void mediate_helper(Rcpp::Environment& env);
RcppExport SEXP _reverseC_mediate_helper(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    mediate_helper(env);
    return R_NilValue;
END_RCPP
}
// threaded_mediate_helper
void threaded_mediate_helper(Rcpp::Environment& env, long long int num_threads);
RcppExport SEXP _reverseC_threaded_mediate_helper(SEXP envSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    Rcpp::traits::input_parameter< long long int >::type num_threads(num_threadsSEXP);
    threaded_mediate_helper(env, num_threads);
    return R_NilValue;
END_RCPP
}
// test
void test(Rcpp::Environment& env);
RcppExport SEXP _reverseC_test(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type env(envSEXP);
    test(env);
    return R_NilValue;
END_RCPP
}
// derp
NumericVector derp(NumericVector x);
RcppExport SEXP _reverseC_derp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(derp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_reverseC_mediate_helper", (DL_FUNC) &_reverseC_mediate_helper, 1},
    {"_reverseC_threaded_mediate_helper", (DL_FUNC) &_reverseC_threaded_mediate_helper, 2},
    {"_reverseC_test", (DL_FUNC) &_reverseC_test, 1},
    {"_reverseC_derp", (DL_FUNC) &_reverseC_derp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_reverseC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
