# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mediate_helper <- function(env) {
    invisible(.Call(`_reverseC_mediate_helper`, env))
}

cpp_mult <- function(m1, m2) {
    .Call(`_reverseC_cpp_mult`, m1, m2)
}

cpp_tmult <- function(m1, m2) {
    .Call(`_reverseC_cpp_tmult`, m1, m2)
}

derp <- function(x) {
    .Call(`_reverseC_derp`, x)
}

