# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mediate_helper <- function(env) {
    invisible(.Call(`_reverseC_mediate_helper`, env))
}

test <- function() {
    invisible(.Call(`_reverseC_test`))
}

derp <- function(x) {
    .Call(`_reverseC_derp`, x)
}

